### ISSUE TITLE
I can not build on Visual Studio 2015

### ISSUE THREAD

**Issue by tgg4ever** [Robinatus/GrepBOTlis#1]
Build version is not working. Browser automaticly changing domain de.grepolis
After I figured out need the change source code and I find the problem
http://prntscr.com/mok4wh

But I can not build this sorry for my bad english. 
http://prntscr.com/mok3f9

**Comment by RobinReinecke** [comment]
Oh ofc. Thats my bad. I will update this repo asap. But I don't have much time at the moment.

**Comment by tgg4ever** [comment]
> Oh ofc. Thats my bad. I will update this repo asap. But I don't have much time at the moment.

Edit:Still not working 
http://prntscr.com/mpuoo5

thank you man I fixed this.
Change domain de. to my region :)
and installed Visual Studio 2017 no problem now thank you so much

**Comment by RobinReinecke** [comment]
Bot may be outdated. I haven't played a while.. I'm gonna test it at the weekend

**Comment by RobinReinecke** [comment]
I updatet the bot. But i didn't run into your issue with farming. You have to debug it by yourself. Please have a look at the Release 1.0
