### ISSUE TITLE
Bot freeze after the game update

### ISSUE THREAD

**Issue by tgg4ever** [Robinatus/GrepBOTlis#2]
Hello  Robin sorry for bother you.
I tried your latest release everything worked fine but 1 week ago game has been patched.
I tried debugging but I find nothing :( I guess my knowledge is inadequate.
can you check the bot on your free time :(
thanks for your excellent job. 

I still trying to figure out bot's working method :))

**Comment by tgg4ever** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/45786331/54679966-af5ec500-4b19-11e9-969a-c33a86f5e74f.png)

**Comment by RobinReinecke** [comment]
Hi,
I'll check it out this weekend. I just tried debugging but got an error in "HttpHandlerOnDownloadStringCompleted", because no SSL Tunnel could be established. Please set a breakpoint there and check out if you get the same error.

**Comment by tgg4ever** [comment]
> Hi,
> I'll check it out this weekend. I just tried debugging but got an error in "HttpHandlerOnDownloadStringCompleted", because no SSL Tunnel could be established. Please set a breakpoint there and check out if you get the same error.

I fix the problem thank you man u re awesome :)
Server connection protocol changed to latest game patch tls11>tls12 
Need the change in mainform
SecurityProtocolType tls12

**Comment by RobinReinecke** [comment]
Awesome! If you'd like, you can create a Pull Request. Or wait until I integrate it.

**Comment by RobinReinecke** [comment]
#3 fixed the issue
